# Generated by Django 5.0.2 on 2024-02-29 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('employee', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roster.shift')),
            ],
        ),
    ]
