# Generated by Django 5.0.2 on 2024-02-29 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='employee_Id',
        ),
    ]
